proxy: #代理请求
  enable: false #是否开启代理
  url: https://service-h5igxl6r-1255944436.bj.apigw.tencentcs.com/release #代理服务链接
key: "BIT101" #加密密钥
verifyCodeExpire: 300 #验证码有效期 单位秒
loginExpire: 2073600 #登录有效期 单位秒
mail: #邮箱
  host: smtp.qq.com
  user: bit101@qq.com
  password:
