port: 9000 #启动端口
proxy: #代理请求
  enable: false #是否开启代理
  url: https://service-h5igxl6r-1255944436.bj.apigw.tencentcs.com/release #代理服务链接
key: "BIT101" #加密密钥
verify_code_expire: 300 #验证码有效期 单位秒
login_expire: 2073600 #登录有效期 单位秒
mail: #邮箱
  host: smtp.qq.com
  user: bit101@qq.com
  password: 
dsn: host=localhost user=bit101 password=BIT101 dbname=bit101 port=5432 sslmode=disable TimeZone=Asia/Shanghai #数据库源
saver: #文件保存相关
  max_size: 24 #最大上传大小 单位MB
  url: "https://bit101-test-1255944436.cos.ap-beijing.myqcloud.com"
  local:
    enable: true
    path: "./data/"
  cos:
    enable: true
    secret_id: ""
    secret_key: ""
    region: "ap-beijing"
    bucket: "bit101-test-1255944436"
    path: "/"
  onedrive:
    enable: true
    api: https://graph.microsoft.com/v1.0/me/drive
    auth_api: https://login.microsoftonline.com/common/oauth2/v2.0/token
    client_id: 
    client_secret: 
    refresh_token: 
default_avatar: "e2e4437695e019484769bc807948dad8.jpeg" #默认头像
paper_page_size: 24 #每次加载文章数量
comment_page_size: 24 #每次加载评论数量
comment_preview_size: 3 #预览子评论数量
course_page_size: 24 #每次加载课程数量
message_page_size: 24
main_url: https://bit101.cn
release_mode: true #是否为部署模式 开启后不显示DEBUG信息